export const VERSION: string = "1.5.4";
export const MAX_PARALLEL_EXECUTIONS: number = 4;
export const MAX_PARALLEL_EXECUTIONS_BATCH: number = 4;
export const MAX_PARALLEL_EXECUTIONS_FETCH: number = 10;
export const MAX_PARALLEL_EXECUTIONS_BATCH_FETCH: number = 10;
export const MAX_QUEUE_SIZE: number = 24;
export const LIFESPAN_IFRAME: number = 1000 * 60 * 1.5; // 1.5 minutes
export const LIFESPAN_TAB: number = 1000 * 10; // 10 seconds
export const DATA_ID_IFRAME: string = "data-mllwtl-frame-crwl-ml";
export const DATA_ID_IFRAME_BATCH: string = "data-mllwtl-frame-batch-crwl-ml";
export const DATA_ID_STRING: string = "data-mllwtl-frame";
export const CEREAL_FRAME_ID: string = "mllwtl-cereal-frame-id";
export const RULE_ID_XFRAME: number = 80045;
export const RULE_ID_CONTENT_DISPOSITION: number = 80046;
export const RULE_ID_CONTENT_TYPE: number = 80047;
export const RULE_ID_VALUE_TO_MODIFY_CONTENT_TYPE_TO: number = 80048;
export const RULE_ID_POST_REQUEST: number = 80049;
export let MAX_DAILY_RATE: number = 500;
export const BADGE_COLOR: string = "#4CAF50";

export const SW_PING_INTERVAL: number = 3 * 1000; // 3 seconds
export const REFRESH_INTERVAL: number = 1000 * 60 * 60 * 24; // 24 hours
export const SPEED_REFRESH_INTERVAL: number = 1000 * 60 * 60 * 12; // 12 hours
